language: node_js
node_js:
  - node
jobs:
  incude:
    - stage: check
      script: npm run lint
    - 
      script: npm run typecheck
    - stage: test
      script: npm test
stages:
  - check
  - test